[
    { "code": "af", "name": "Afrikaans" },
    { "code": "sq", "name": "Albanian" },
    { "code": "ar", "name": "Arabic" },
    { "code": "hy", "name": "Armenian" },
    { "code": "az", "name": "Azerbaijani" },
    { "code": "eu", "name": "Basque" },
    { "code": "be", "name": "Belarusian" },
    { "code": "bn", "name": "Bengali" },
    { "code": "bg", "name": "Bulgarian" },
    { "code": "ca", "name": "Catalan" },
    { "code": "zh-CN", "name": "Chinese (Simplified)" },
    { "code": "zh-TW", "name": "Chinese (Traditional)" },
    { "code": "hr", "name": "Croatian" },
    { "code": "cs", "name": "Czech" },
    { "code": "da", "name": "Danish" },
    { "code": "nl", "name": "Dutch" },
    { "code": "en", "name": "English" },
    { "code": "et", "name": "Estonian" },
    { "code": "fi", "name": "Finnish" },
    { "code": "fr", "name": "French" },
    { "code": "de", "name": "German" },
    { "code": "el", "name": "Greek" },
    { "code": "he", "name": "Hebrew" },
    { "code": "hi", "name": "Hindi" },
    { "code": "hu", "name": "Hungarian" },
    { "code": "id", "name": "Indonesian" },
    { "code": "it", "name": "Italian" },
    { "code": "ja", "name": "Japanese" },
    { "code": "ko", "name": "Korean" },
    { "code": "no", "name": "Norwegian" },
    { "code": "pl", "name": "Polish" },
    { "code": "pt", "name": "Portuguese" },
    { "code": "ro", "name": "Romanian" },
    { "code": "ru", "name": "Russian" },
    { "code": "es", "name": "Spanish" },
    { "code": "sv", "name": "Swedish" },
    { "code": "th", "name": "Thai" },
    { "code": "tr", "name": "Turkish" },
    { "code": "uk", "name": "Ukrainian" },
    { "code": "vi", "name": "Vietnamese" }
]